development:
  adapter: postgresql
  database: pe_development
  username: Ricky
  password:
  encoding: utf8
  pool: 5

test: &test
  adapter: postgresql
  database: pe_test
  username: Ricky
  password:
  encoding: utf8
  pool: 5

cucumber:
  <<: *test

production:
  adapter: postgresql
  encoding: unicode
  database: pe_production
  pool: 5
